### ISSUE TITLE
How to use with css background images?

### ISSUE THREAD

**Issue by danielLee0721** [11ty/eleventy-img#46]
How do I use this plugin for css background images?

Thank you so much in advance!

**Comment by MrKrautee** [comment]
- use inline css for the ability to use template language in css files:

``` nunjucks
  {% set css %}
    {% include "assets/css/styles.css" %}
  {% endset %}
  <style>{{ css | safe }}</style>
```
- define a cssBackgroundShortcode which generates css media queries for each src and viewport in srcset ...
  should be returning something like this:
```  css 
        #image { 
            background-image: url(largeimage.jpg); 
        }
        @media only screen and (max-width: 320px) {
            #image { 
                background-image: url(smallimage.jpg); 
            }
        }
```
- use shortcode in your css file

I hope it will help you, if I implement a cssBackgroundShortcode, I will share it!
